#ifndef _CONFIG_H
#define _CONFIG_H

#include <Arduino.h>

// #define DEBUG
#define ENABLE_COMMUNICATION

// Task scheduler configuration
#define _TASK_PRIORITY
// #define _TASK_WDT_IDS
#define _TASK_TIMECRITICAL
#define _TASK_SLEEP_ON_IDLE_RUN
//#define _TASK_SELF_DESTRUCT
#define _TASK_LTS_POINTER
#include <TaskSchedulerDeclarations.h>

// Pin configuration
#define NORTH_SENSOR A0
#define SOUTH_SENSOR A1
#define EAST_SENSOR A2
#define WEST_SENSOR A3
#define WIND_SENSOR A4
#define LED 13

#define NORTH_SWITCH 3
#define SOUTH_SWITCH 4
#define EAST_SWITCH 6
#define WEST_SWITCH 7
#define NORTH_LIMIT_SWITCH 2
#define SOUTH_LIMIT_SWITCH 5

#define TM_STROBE 8
#define TM_CLOCK 9
#define TM_DIO 10
#define TM_HIGH_FREQ false

#define EPSILON 100
#define DARK_LIMIT 50
#define WIND_LIMIT 100
#define WIND_SAMPLES 5

#define MOTOR_MOVEMENT_TIME 100 * TASK_MILLISECOND
#define GO_HOME_MOVEMENT_TIME 30 * TASK_SECOND

#define HOME_SLEEP_TIME 2 * TASK_HOUR

#define SENSOR_CHECK_INTERVAL 8 * TASK_SECOND
#define COMMUNICATION_INTERVAL 10 * TASK_SECOND
#define WIND_CHECK_INTERVAL 5 * TASK_SECOND
#define BUTTONS_CHECK_INTERVAL 1 * TASK_SECOND
#define BUTTONS_CHECK_INTERVAL_MANUAL 100 * TASK_MILLISECOND
#define DISPLAY_CYCLE_INTERVAL 2 * TASK_SECOND

#endif
